import fs from "node:fs/promises";
import type { AgnosConfig, CliCommand, ResolveContext } from "../../../core/index.js";
import { readConfigOrDefault, runDomainInitSteps, writeConfig } from "../../../core/index.js";
import { readEffectiveDocsConfig } from "../effective-config.js";
import { DEFAULT_DOCS_METADATA } from "../schema.js";
import { runGenerate } from "./generate.js";

export const init: CliCommand = {
  description:
    "Prompt for docs configuration, create the docs directory, seed agnos.json#docs.metadata, then generate the autogenerated files",
  async run(_args, ctx) {
    // Import the plugin lazily to avoid the circular load at module init time.
    const { default: docsPlugin } = await import("../index.js");
    await runDomainInitSteps(docsPlugin, ctx, {
      yes: false,
      dryRun: ctx.dryRun ?? false,
    });
    await runInit(ctx);
  },
};

export async function runInit(ctx: ResolveContext): Promise<void> {
  const cfg = await readEffectiveDocsConfig(ctx);
  await fs.mkdir(cfg.route, { recursive: true });

  await seedDefaultMetadata(ctx);

  // Re-read so the freshly-seeded metadata drives generation.
  const next = await readEffectiveDocsConfig(ctx);
  await runGenerate(next, ctx);
}

/**
 * Write the default metadata schema into `agnos.json#docs.metadata` if the user
 * hasn't set it. Makes the schema discoverable and editable from the config file.
 * Idempotent: skips when `metadata` is already present.
 */
async function seedDefaultMetadata(ctx: ResolveContext): Promise<void> {
  const config = (await readConfigOrDefault(ctx.configPath)) as AgnosConfig;
  const docsBlock = (config.docs ?? {}) as Record<string, unknown>;
  if (docsBlock["metadata"]) return;

  if (ctx.dryRun) {
    ctx.logger.info(`would: seed default docs.metadata into agnos.json`);
    return;
  }

  const nextConfig: AgnosConfig = {
    ...config,
    docs: { ...docsBlock, metadata: DEFAULT_DOCS_METADATA },
  };
  await writeConfig(ctx.configPath, nextConfig);
  ctx.logger.info(`seeded default docs.metadata into agnos.json`);
}
