export function starterIndex(): string {
  return `---
title: Documentation Index
description: Auto-generated index of project documentation.
read_when: You need a map of the documentation.
agent_cant: write
---

<!-- agnos-docs:autogenerated — do not edit by hand; run \`agnos docs generate\` -->

_No documentation yet. Add markdown files under this directory and run \`agnos docs generate\`._
`;
}

export function starterContent(): string {
  return `---
title: Documentation Content
description: Auto-generated concatenation of project documentation.
read_when: You want everything in one place.
agent_cant: write
---

<!-- agnos-docs:autogenerated — do not edit by hand; run \`agnos docs generate\` -->
`;
}

export function starterDocRules(): string {
  return `---
title: Documentation Rules
description: How AI agents should interact with documentation in this project.
read_when: Before reading or modifying documentation.
agent_cant: write
---

When working with documentation in this project:

- Every markdown file under the docs directory must include frontmatter with: \`title\`, \`description\`, \`read_when\`, and \`agent_cant\`.
- Use the index (see "Documentation Index" below) to find docs by topic.
- Never edit \`index.md\` or \`content.md\` by hand — they are regenerated by \`agnos docs generate\`.
`;
}
