import type { EffectiveDocsConfig } from "./effective-config.js";

const SLOT_PATTERN = /<!--agnos:slot:([a-z_]+)-->/g;

export function renderTemplate(template: string, slots: Record<string, string>): string {
  let out = template;
  for (const [name, value] of Object.entries(slots)) {
    const token = `<!--agnos:slot:${name}-->`;
    if (!out.includes(token)) {
      throw new Error(`template missing declared slot: ${name}`);
    }
    out = out.split(token).join(value);
  }
  const leftover = out.match(SLOT_PATTERN);
  if (leftover) {
    throw new Error(`template has unsubstituted slots: ${leftover.join(", ")}`);
  }
  return out;
}

export function renderFrontmatter(
  cfg: EffectiveDocsConfig,
  values: Record<string, string>,
): string {
  return Object.keys(cfg.metadata)
    .map((key) => `${key}: ${values[key] ?? ""}`)
    .join("\n");
}

export function renderRequiredFields(cfg: EffectiveDocsConfig): string {
  return Object.entries(cfg.metadata)
    .map(([key, desc]) => `  - \`${key}\` — ${desc}`)
    .join("\n");
}

export const indexTemplate = `---
<!--agnos:slot:frontmatter-->
---

<!-- agnos-docs:autogenerated — do not edit by hand; run \`agnos docs generate\` -->

<!--agnos:slot:body-->
`;

export const contentTemplate = `---
<!--agnos:slot:frontmatter-->
---

<!-- agnos-docs:autogenerated — do not edit by hand; run \`agnos docs generate\` -->

<!--agnos:slot:body-->
`;

export const docRulesTemplate = `---
<!--agnos:slot:frontmatter-->
---

<!-- agnos-docs:autogenerated — do not edit by hand; run \`agnos docs generate\` -->

When working with documentation in this project:

- Every markdown file under the docs directory must include frontmatter with the following fields:

<!--agnos:slot:required_fields-->

- Use the index (see "Documentation Index" below) to find docs by topic.
- Never edit \`index.md\`, \`content.md\`, or \`doc-rules.md\` by hand — they are regenerated by \`agnos docs generate\`.
`;

export const INDEX_VALUES: Record<string, string> = {
  title: "Documentation Index",
  description: "Auto-generated index of project documentation.",
  read_when: "You need a map of the documentation.",
  agent_cant: "write",
};

export const CONTENT_VALUES: Record<string, string> = {
  title: "Documentation Content",
  description: "Auto-generated concatenation of project documentation.",
  read_when: "You want everything in one place.",
  agent_cant: "write",
};

export const DOC_RULES_VALUES: Record<string, string> = {
  title: "Documentation Rules",
  description: "How AI agents should interact with documentation in this project.",
  read_when: "Before reading or modifying documentation.",
  agent_cant: "write",
};
