import fs from "node:fs/promises";
import path from "node:path";
import matter from "gray-matter";
import type { CliCommand, ResolveContext } from "@agnos/core";
import { readEffectiveDocsConfig, type EffectiveDocsConfig } from "../effective-config.js";
import { listUserDocs } from "./validate.js";

export const generate: CliCommand = {
  description: "Regenerate index.md (TOC) and content.md (concatenation) from user docs",
  async run(_args, ctx) {
    const cfg = await readEffectiveDocsConfig(ctx);
    await runGenerate(cfg, ctx);
  },
};

export async function runGenerate(cfg: EffectiveDocsConfig, ctx: ResolveContext): Promise<{ indexChanged: boolean; contentChanged: boolean }> {
  const files = await listUserDocs(cfg);
  const docs = await Promise.all(files.map((abs) => readDoc(abs, cfg)));
  docs.sort(compareDocs);

  const indexText = renderIndex(docs, cfg);
  const indexChanged = await writeIfChanged(cfg.indexFile, indexText, ctx);

  let contentChanged = false;
  if (cfg.contentFile) {
    const contentText = renderContent(docs, cfg);
    contentChanged = await writeIfChanged(cfg.contentFile, contentText, ctx);
  }
  return { indexChanged, contentChanged };
}

interface DocEntry {
  absolutePath: string;
  relativeFromRoute: string;
  topDir: string;
  title: string;
  description: string;
  body: string;
}

async function readDoc(abs: string, cfg: EffectiveDocsConfig): Promise<DocEntry> {
  const raw = await fs.readFile(abs, "utf8");
  const parsed = matter(raw);
  const data = (parsed.data ?? {}) as Record<string, unknown>;
  const relativeFromRoute = path.relative(cfg.route, abs).split(path.sep).join("/");
  const segments = relativeFromRoute.split("/");
  const topDir = segments.length > 1 ? segments[0]! : "";
  return {
    absolutePath: abs,
    relativeFromRoute,
    topDir,
    title: typeof data["title"] === "string" ? data["title"] : path.basename(abs, ".md"),
    description: typeof data["description"] === "string" ? data["description"] : "",
    body: parsed.content.trim(),
  };
}

function compareDocs(a: DocEntry, b: DocEntry): number {
  if (a.topDir === b.topDir) return a.relativeFromRoute.localeCompare(b.relativeFromRoute);
  if (a.topDir === "") return -1;
  if (b.topDir === "") return 1;
  return a.topDir.localeCompare(b.topDir);
}

function renderIndex(docs: DocEntry[], cfg: EffectiveDocsConfig): string {
  const lines: string[] = [];
  lines.push("---");
  lines.push("title: Documentation Index");
  lines.push("description: Auto-generated index of project documentation.");
  lines.push("read_when: You need a map of the documentation.");
  lines.push("agent_cant: write");
  lines.push("---");
  lines.push("");
  lines.push("<!-- agnos-docs:autogenerated — do not edit by hand; run `agnos docs generate` -->");
  lines.push("");

  if (docs.length === 0) {
    lines.push("_No documentation yet. Add markdown files under this directory and run `agnos docs generate`._");
    return lines.join("\n") + "\n";
  }

  const grouped = new Map<string, DocEntry[]>();
  for (const d of docs) {
    const sectionKey = d.topDir === "" ? "Overview" : capitalizeSection(d.topDir);
    const arr = grouped.get(sectionKey) ?? [];
    arr.push(d);
    grouped.set(sectionKey, arr);
  }
  // stable section order: "Overview" first if present, then others alphabetical
  const sectionOrder = [...grouped.keys()].sort((a, b) => {
    if (a === "Overview") return -1;
    if (b === "Overview") return 1;
    return a.localeCompare(b);
  });

  for (const section of sectionOrder) {
    lines.push(`## ${section}`);
    const items = grouped.get(section) ?? [];
    for (const d of items) {
      const desc = d.description ? `: ${d.description}` : "";
      lines.push(`- [${d.title}](${d.relativeFromRoute})${desc}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

function renderContent(docs: DocEntry[], _cfg: EffectiveDocsConfig): string {
  const lines: string[] = [];
  lines.push("---");
  lines.push("title: Documentation Content");
  lines.push("description: Auto-generated concatenation of project documentation.");
  lines.push("read_when: You want everything in one place.");
  lines.push("agent_cant: write");
  lines.push("---");
  lines.push("");
  lines.push("<!-- agnos-docs:autogenerated — do not edit by hand; run `agnos docs generate` -->");
  lines.push("");
  for (let i = 0; i < docs.length; i++) {
    const d = docs[i]!;
    if (i > 0) {
      lines.push("");
      lines.push("---");
      lines.push("");
    }
    lines.push(`# ${d.title}`);
    lines.push(`_Source: ${d.relativeFromRoute}_`);
    lines.push("");
    lines.push(d.body);
  }
  return lines.join("\n") + "\n";
}

function capitalizeSection(dir: string): string {
  return dir
    .split(/[-_]/g)
    .filter(Boolean)
    .map((word) => word[0]!.toUpperCase() + word.slice(1))
    .join(" ");
}

async function writeIfChanged(file: string, text: string, ctx: ResolveContext): Promise<boolean> {
  let existing: string | null = null;
  try {
    existing = await fs.readFile(file, "utf8");
  } catch {
    existing = null;
  }
  if (existing === text) return false;
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, text, "utf8");
  ctx.logger.info(`  wrote ${path.relative(ctx.projectRoot, file)}`);
  return true;
}
